### ISSUE TITLE
Make Spatial and Multi-omics working group inactive

### ISSUE THREAD

**Issue by stephaniehicks** [Bioconductor/BiocWorkingGroups#34]
Hi, 

I am currently the lead for the Spatial and Multi-omics working group. I'm interested in stepping down from this role. I have not been able to identify anyone who would be willing to take this role over. Therefore, I understand it will go inactive. I would gladly welcome anyone interested in this role though! 

Please let me know what I can do to support this request. 

Thanks! 
Stephanie

**Comment by lshep** [comment]
Yes I'll try to get to this sometime this week.  I needed to move some other working groups around too

**Comment by stephaniehicks** [comment]
Thanks @lshep!

**Comment by stephaniehicks** [comment]
hi, just wanted to nudge this @lshep. Thanks!

**Comment by lshep** [comment]
@stephaniehicks  yes sorry ,  I've had updating the entire site on my to-do for awhile -- I'll make sure it gets done by end of next week ...

**Comment by stephaniehicks** [comment]
No worries @lshep! I totally understand. I appreciate your help with this!

**Comment by lshep** [comment]
done. sorry it took so long

**Comment by stephaniehicks** [comment]
thank you!
